### ISSUE TITLE
Undefined symbol: _OBJC_CLASS_$_RNPermissionHandlerCamera

### ISSUE THREAD

**Issue by ShanmugapriyaKesavan** [zoontek/react-native-permissions#555]
xcode error: 
Undefined symbol: _OBJC_CLASS_$_RNPermissionHandlerCamera

Pod File: 
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Seller' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'SellerTests' do
    inherit! :complete
    # Pods for testing
    # Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Seller-tvOS' do
  # Pods for Seller-tvOS

  target 'Seller-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

**Comment by mikehardy** [comment]
https://github.com/zoontek/react-native-permissions/blob/8fdfbc2c83f54010529bb262983aff4343721ad1/example/ios/Podfile#L32

The example uses it and it works, you have a project-specific problem that will not involve any changes to this module so it is likely not a bug.

Examine the example vs your project and fix as needed. Note that `npx react-native-clean-project` may help in case it was a stale Xcode build cache.

**Comment by ShanmugapriyaKesavan** [comment]
Thanks for your response @mikehardy ..

Got it fixed by manually adding "RNPermissionHandlerCamera.m" file in "Compiler sources" inside "Build Phases" in Xcode..

**Comment by mikehardy** [comment]
FWIW, that sounds like a fix in the wrong direction. Nothing like that is supposed to be necessary
I believe if you examine the example you will see that it does not manually add any source to build phases anywhere, cocoapods integration is supposed to handle that

perhaps you forgot `pod install`

**Comment by egealpay** [comment]
I did `pod install`. However, RNPermissionHandlerCamera.m file was not in "Compiler sources" inside "Build Phases" in Xcode. My Podfile:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'QRScanner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'QRScannerTests' do
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'QRScanner-tvOS' do
  # Pods for QRScanner-tvOS

  target 'QRScanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```

Any comment?
