### ISSUE TITLE
Android - permissions doesn't display Alert window

### ISSUE THREAD

**Issue by MariaPereiraMindera** [zoontek/react-native-permissions#611]
## Summary

Whenever I install the application, the pop up asking for permissions does not appear, but they are granted and appear in the application settings.

## Environment info
`react-native info` output:
```bash
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.60 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_275 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.2 => 0.63.2
```

Library version: 3.0.4

## Steps to reproduce
AndroidManifest.xml
```
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```

App.js
```
    requestMultiple([
      PERMISSIONS.ANDROID.CAMERA,
      PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
      PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
    ]).then((statuses) => {
      if (statuses[PERMISSIONS.ANDROID.CAMERA] === RESULTS.GRANTED) {
        (...)
      }
    });
```

**Comment by zoontek** [comment]
@MariaPereiraMindera Maybe you already granted them? I need more infos. Which device are you using? Which Android version?

**Comment by vunguyen112** [comment]
@zoontek  I got the same problem. I'm using nokia 7.2 android 10.

**Comment by zoontek** [comment]
@vunguyen112 Does it works when you build the example app (clone this repo, it's in `/example`)?

**Comment by zoontek** [comment]
I just gave it a try using the provided code:

```js
requestMultiple([
  PERMISSIONS.ANDROID.CAMERA,
  PERMISSIONS.ANDROID.READ_EXTERNAL_STORAGE,
  PERMISSIONS.ANDROID.WRITE_EXTERNAL_STORAGE,
])
  .then((statuses) => console.warn(statuses))
  .catch((error) => console.warn(error));
```

No issues.

https://user-images.githubusercontent.com/1902323/120457529-d0c4c800-c396-11eb-9f7c-a9bbe12b581c.mp4

The Alert is correctly displayed. It ask me about `CAMERA` and `WRITE_EXTERNAL_STORAGE` (which also grant `READ_EXTERNAL_STORAGE` - using both is useless in this case)

After that, if I restart the app, the non requestables permissions are ignored, following the documentation schema: https://github.com/zoontek/react-native-permissions#android-flow (they are granted, no need to prompt the user)

So everything seems normal? But maybe I didn't understand something? @vunguyen112 @MariaPereiraMindera could you be a bit more specific about your issue here (with a video, for example)?

**Comment by gillbeits** [comment]
@MariaPereiraMindera Same issue. Fixed by ignore expo-permissions in package.json.
```json
"react-native-unimodules": {
    "android": {
      "exclude": [
        "expo-permissions"
      ]
    }
  }
```

**Comment by zoontek** [comment]
I could not reproduce this, so I'm closing it

**Comment by jzxchiang1** [comment]
For posterity, this is most likely an insane bug with gradle / RN as documented here: https://github.com/facebook/react-native/issues/31278

The fix is the comment I left in the bug.

**Comment by mikehardy** [comment]
@jzxchiang1 wow, that is unexpected. Your comment suggests downgrading. I suggest that current 4.2.x gradle plugin (upgrading) also works and is likely a safer approach. I can also confirm Android Gradle Plugin 7 works as well, with gradle 7.1.1 (both current stable now) but only with this tiny patch https://github.com/react-native-community/cli/pull/1396 (included in upcoming react-native 0.65) and a switch to JDK11 if you just want to move everything forward to current stable tools while you (or anyone else trying to fix this) is in their gradle files working

**Comment by princefishthrower** [comment]
@jzxchiang1  @mikehardy I've upgraded to React Native 0.66.0, Gradle plugin 7.0.1, Gradle 7.2 - I still don't see the alert window. Is there still a step I'm missing? I'm calling:

```
await request(PERMISSIONS.ANDROID.CAMERA);
```

Or is this anyway an issue with the Android emulator in that you don't have camera access anyway? I seem to remember something like that with iOS...

**Comment by mikehardy** [comment]
Android emulator has a camera (normally, unless you remove it in the emulator settings?) and permissions for it do work correctly (unless you have already granted them? check settings). I've tested this recently (on emulators and device with fresh installs of my app) and I do see camera permissions requests on emulator

**Comment by princefishthrower** [comment]
@mikehardy - indeed, I was missing a step. I can also confirm this now works. My issue was that I forgot to include 

```xml
<uses-permission android:name="android.permission.CAMERA"/>
```

in my `android/app/src/main/AndroidManifest.xml`
